<a href="https://colab.research.google.com/github/maithstartup/Notebooks-Practical-ML-Beginners/blob/master/numpy/3_Sampling_Methods.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

### set seed

In [2]:
np.random.seed(123)

In [3]:
np.random.randn(5) # array([-1.0856306 ,  0.99734545,  0.2829785 , -1.50629471, -0.57860025])

array([-1.0856306 ,  0.99734545,  0.2829785 , -1.50629471, -0.57860025])

In [4]:
np.random.randn(5) #array([ 1.65143654, -2.42667924, -0.42891263,  1.26593626, -0.8667404 ])

array([ 1.65143654, -2.42667924, -0.42891263,  1.26593626, -0.8667404 ])

### set random state which is independent from the global seed

In [5]:
rs = np.random.RandomState(28)
rs.rand(10)

array([0.72901374, 0.5612396 , 0.12496709, 0.39759237, 0.78130821,
       0.51099298, 0.18269336, 0.85351288, 0.95537189, 0.98421347])

In [6]:
rs.rand(10)

array([0.19270097, 0.9707951 , 0.23480835, 0.02635385, 0.94606034,
       0.92172485, 0.29397577, 0.1662737 , 0.39542284, 0.51066973])

### generate a random sample from interval [0, 1) in a given shape

In [7]:
# generate a 1-D array
print(np.random.rand(3))           

[0.43857224 0.0596779  0.39804426]


In [8]:
# generate a 2-D array
print(np.random.rand(3,3))          

[[0.73799541 0.18249173 0.17545176]
 [0.53155137 0.53182759 0.63440096]
 [0.84943179 0.72445532 0.61102351]]


### generate a sample from the standard normal distribution (mean = 0, var = 1)

In [9]:
val=np.random.randn(3,3)

In [10]:
val

array([[-0.93583387,  1.17582904, -1.25388067],
       [-0.6377515 ,  0.9071052 , -1.4286807 ],
       [-0.14006872, -0.8617549 , -0.25561937]])

### generate an array of random integers in a given interval [low, high)

In [11]:
# np.ranodm.randint(low, high, size, dtype)
np.random.randint(1, 50, 5, 'i8')

array([14, 19, 37, 16, 44])

### generate an array of random floating-point numbers in the interval [0.0, 1.0)

In [12]:
# the following methods are the same as np.random.rand()
print(np.random.random_sample(10))

print(np.random.random(10))
print(np.random.ranf(10))
print(np.random.sample(10))

[0.7503787  0.69340324 0.51176338 0.46426806 0.56843069 0.30254945
 0.49730879 0.68326291 0.91669867 0.10892895]
[0.49549179 0.23283593 0.43686066 0.75154299 0.48089213 0.79772841
 0.28270293 0.43341824 0.00975735 0.34079598]
[0.68927201 0.86936929 0.26780382 0.45674792 0.26828131 0.8370528
 0.27051466 0.53006201 0.17537266 0.31496645]
[0.8911091  0.18033628 0.4943162  0.2122981  0.52087687 0.16009994
 0.9190568  0.99428992 0.47704756 0.30988351]


### generate a random sample from a given 1-D array

In [13]:
# np.random.choice(iterable_or_int, size, replace=True, p=weights)
print(np.random.choice(range(3), 10, replace=True, p=[0.2, 0.5, 0.3]))

[1 1 2 0 1 2 1 1 2 2]


In [14]:
print(np.random.choice(3, 10))

[1 0 2 0 0 2 0 2 1 0]


In [15]:
print(np.random.choice([1,2,3], 10))

[1 1 1 1 1 2 1 1 1 3]


### shuffle an array in place

In [16]:
arr = np.array(range(10))
print(arr)

[0 1 2 3 4 5 6 7 8 9]


In [17]:
np.random.shuffle(arr)
print(arr)

[4 7 3 5 2 0 9 1 6 8]


### generate a permutation of an array

In [18]:
# similar to np.random.shuffle(), but it returns a copy rather than making changes in place
arr = np.array(range(10))
print('The initial array: ', arr)
print('A permutation of the array: ', np.random.permutation(arr))
print(arr)

The initial array:  [0 1 2 3 4 5 6 7 8 9]
A permutation of the array:  [2 0 6 8 9 3 4 5 7 1]
[0 1 2 3 4 5 6 7 8 9]


In [19]:
np.random.seed(26)
  
# print a random number between 1 and 1000. 
print(np.random.randint(1, 1000)) 
  
# if you want to get the same random number again then, 
np.random.seed(26)  
print(np.random.randint(1, 1000)) 
  
# If seed function is not used 
  
# Gives totally unpredictable responses. 
print(np.random.randint(1, 1000)) 

822
822
319
