<a href="https://colab.research.google.com/github/maithstartup/Notebooks-Practical-ML-Beginners/blob/master/numpy/4_Math_Functions.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

### Math Functions 

In [1]:
import numpy as np

In [2]:
np.random.seed(26)
arr = np.random.choice(range(1,5), 10, replace=True)
arr=arr.reshape(2,5)

In [3]:
arr

array([[2, 3, 3, 1, 2],
       [3, 4, 2, 3, 1]])

### element-wise addition, subtraction, multiplication and division

In [4]:
print(arr + 10)
print(arr - 10)
print(arr * 10)
print(arr / 10)

[[12 13 13 11 12]
 [13 14 12 13 11]]
[[-8 -7 -7 -9 -8]
 [-7 -6 -8 -7 -9]]
[[20 30 30 10 20]
 [30 40 20 30 10]]
[[0.2 0.3 0.3 0.1 0.2]
 [0.3 0.4 0.2 0.3 0.1]]


In [5]:
# the above operations can be performed using numpy built-in functions
# which can save memory as the output can be stored in the original array rather than assigning new memory
arr1 = np.array([1,2,3])
np.add(arr1, [8,9,10], out=arr1)
print(arr1)

np.subtract(arr1, [8,9,10], out=arr1)
print(arr1)

np.multiply(arr1, [1,2,3], out=arr1)
print(arr1)

[ 9 11 13]
[1 2 3]
[1 4 9]


### element-wise exponentiation

In [6]:
print(np.exp(arr))

[[ 7.3890561  20.08553692 20.08553692  2.71828183  7.3890561 ]
 [20.08553692 54.59815003  7.3890561  20.08553692  2.71828183]]


### element-wise logorithm

In [7]:
# natural log
print(np.log(arr))      

[[0.69314718 1.09861229 1.09861229 0.         0.69314718]
 [1.09861229 1.38629436 0.69314718 1.09861229 0.        ]]


In [8]:
# base 2
print(np.log2(arr))     

[[1.        1.5849625 1.5849625 0.        1.       ]
 [1.5849625 2.        1.        1.5849625 0.       ]]


In [9]:
# base 10
print(np.log10(arr))    

[[0.30103    0.47712125 0.47712125 0.         0.30103   ]
 [0.47712125 0.60205999 0.30103    0.47712125 0.        ]]


### element-wise square root

In [10]:
print(np.sqrt(arr))

[[1.41421356 1.73205081 1.73205081 1.         1.41421356]
 [1.73205081 2.         1.41421356 1.73205081 1.        ]]


### element-wise sine and cosine

In [11]:
print(np.sin(arr))


[[ 0.90929743  0.14112001  0.14112001  0.84147098  0.90929743]
 [ 0.14112001 -0.7568025   0.90929743  0.14112001  0.84147098]]


In [12]:
print(np.cos(arr))

[[-0.41614684 -0.9899925  -0.9899925   0.54030231 -0.41614684]
 [-0.9899925  -0.65364362 -0.41614684 -0.9899925   0.54030231]]


### sum along a specified axis

In [13]:
arr

array([[2, 3, 3, 1, 2],
       [3, 4, 2, 3, 1]])

In [14]:
# sum along the row
print(np.sum(arr, axis=0))    

[5 7 5 4 3]


In [15]:
# sum along the column
print(np.sum(arr, axis=1))    

[11 13]


### compute the min and max along a specified axis

In [16]:
# calculate min along the row
print(np.min(arr, axis=0))

[2 3 2 1 1]


In [17]:
# calculate max along the column
print(np.max(arr, axis=1))    

[3 4]


In [18]:
# if axis not specified, calculate the max/min value of all elements
print(np.max(arr))
print(np.min(arr))

4
1


### compute the indices of the min and max along a specified axis

In [19]:
arr

array([[2, 3, 3, 1, 2],
       [3, 4, 2, 3, 1]])

In [20]:
# along the row
print(np.argmin(arr, axis=0))
print(np.argmax(arr, axis=0))

[0 0 1 0 1]
[1 1 0 1 0]


In [21]:
# along the column
print(np.argmin(arr, axis=1))
print(np.argmax(arr, axis=1))

[3 4]
[1 1]


In [22]:
# if axis not specified, return the index of the flattened array
print(np.argmin(arr))
print(np.argmax(arr))

3
6


### compute element-wise min and max of two arrays

In [23]:
arr.flatten()

array([2, 3, 3, 1, 2, 3, 4, 2, 3, 1])

In [24]:
arr1 = np.array([1, 3, 5, 7, 9])
arr2 = np.array([0, 4, 3, 8, 7])
print(np.maximum(arr1, arr2))
print(np.minimum(arr1, arr2))

[1 4 5 8 9]
[0 3 3 7 7]


### split fractional and integral parts of a floating-point array

In [25]:
arr1 = np.random.rand(10) * 10
re, intg = np.modf(arr1)
print(arr1)
print('fractional: ', re)
print('integral: ', intg)

[1.87921392 2.69505246 4.96192141 7.39121747 1.94951992 1.79745247
 5.38826259 2.82765605 7.60939869 2.69692942]
fractional:  [0.87921392 0.69505246 0.96192141 0.39121747 0.94951992 0.79745247
 0.38826259 0.82765605 0.60939869 0.69692942]
integral:  [1. 2. 4. 7. 1. 1. 5. 2. 7. 2.]


### compute the mean

In [26]:
arr

array([[2, 3, 3, 1, 2],
       [3, 4, 2, 3, 1]])

In [27]:
# compute the overall mean
print(np.mean(arr))

2.4


In [28]:
# compute the mean along the row
print(np.mean(arr, axis=0))   

[2.5 3.5 2.5 2.  1.5]


In [29]:
# compute the mean along the column
print(np.mean(arr, axis=1)) 

[2.2 2.6]


### compute the median

In [30]:
# compute the overall median
print(np.median(arr))

2.5


In [31]:
# compute the median along the row
print(np.median(arr, axis=0)) 

[2.5 3.5 2.5 2.  1.5]


In [32]:
# compute the median along the column
print(np.median(arr, axis=1))

[2. 3.]


In [33]:
np.info(arr)

### compute the percentile

In [34]:
arr1 = np.random.rand(100)
# compute 5, 65, and 95 percentiles of the array
print(np.percentile(arr1, [5, 50, 95]))
np.median(arr1)

[0.0664878  0.5247998  0.97370776]


0.5247998036431495

### compute the standard deviation & variance

In [35]:
# compute the overall standard deviation
print(np.std(arr))

0.9165151389911681


In [36]:
# compute the standard deviation along the row
print(np.std(arr, axis=0))

[0.5 0.5 0.5 1.  0.5]


In [37]:
# compute the standard deviation along the column
print(np.std(arr, axis=1))

[0.74833148 1.0198039 ]


In [38]:
# compute the overall variance
print(np.var(arr))

0.8400000000000001


In [39]:
# compute the variance along the row
print(np.var(arr, axis=0))

[0.25 0.25 0.25 1.   0.25]


In [40]:
# compute the variance along the column
print(np.var(arr, axis=1))

[0.56 1.04]


### compute the covariance & correlation

In [41]:
arr = np.random.rand(5,8)

In [42]:
print(np.cov(arr))

[[ 0.0267089   0.04774314  0.01642168 -0.0465569  -0.01952218]
 [ 0.04774314  0.1159078   0.0357572  -0.08099411 -0.02276277]
 [ 0.01642168  0.0357572   0.07252431 -0.05289587 -0.01209068]
 [-0.0465569  -0.08099411 -0.05289587  0.12586242 -0.00477081]
 [-0.01952218 -0.02276277 -0.01209068 -0.00477081  0.08589177]]


In [43]:
print(np.corrcoef(arr[:,0], arr[:,1]))

[[1.         0.59678819]
 [0.59678819 1.        ]]


### compute cumulative sum & product

In [44]:
arr = np.random.choice(range(1,5), 10, replace=True).reshape(2,5)

In [45]:
arr

array([[4, 1, 2, 3, 4],
       [2, 2, 4, 1, 2]])

In [46]:
# calculate the cumulative sums along the row
print(np.cumsum(arr, axis=0))    

[[4 1 2 3 4]
 [6 3 6 4 6]]


In [47]:
# calculate the cumulative sums along the column
print(np.cumsum(arr, axis=1))    

[[ 4  5  7 10 14]
 [ 2  4  8  9 11]]


In [48]:
# calculate the cumulative product along the row
print(np.cumprod(arr, axis=0))   

[[4 1 2 3 4]
 [8 2 8 3 8]]


In [49]:
# calculate the cumulative product along the column
print(np.cumprod(arr, axis=1))  

[[ 4  4  8 24 96]
 [ 2  4 16 16 32]]


### element-wise 


In [50]:
arr1 = np.array([1,2,3,4,5])
arr2 = np.array([5,4,3,2,1])

In [51]:
# return an array of bools
print(arr1 == arr2)    
print(arr1 < 3)

[False False  True False False]
[ True  True False False False]


### Matrix Multiplication

In [52]:
arr1 = np.arange(0,25).reshape(5,5)
arr2 = np.arange(0,35).reshape(5,7)

In [53]:
print(arr1.dot(arr2))
# or
print(np.dot(arr1, arr2))
# or
print(arr1 @ arr2)
# or
print(np.matmul(arr1,arr2))

[[ 210  220  230  240  250  260  270]
 [ 560  595  630  665  700  735  770]
 [ 910  970 1030 1090 1150 1210 1270]
 [1260 1345 1430 1515 1600 1685 1770]
 [1610 1720 1830 1940 2050 2160 2270]]
[[ 210  220  230  240  250  260  270]
 [ 560  595  630  665  700  735  770]
 [ 910  970 1030 1090 1150 1210 1270]
 [1260 1345 1430 1515 1600 1685 1770]
 [1610 1720 1830 1940 2050 2160 2270]]
[[ 210  220  230  240  250  260  270]
 [ 560  595  630  665  700  735  770]
 [ 910  970 1030 1090 1150 1210 1270]
 [1260 1345 1430 1515 1600 1685 1770]
 [1610 1720 1830 1940 2050 2160 2270]]
[[ 210  220  230  240  250  260  270]
 [ 560  595  630  665  700  735  770]
 [ 910  970 1030 1090 1150 1210 1270]
 [1260 1345 1430 1515 1600 1685 1770]
 [1610 1720 1830 1940 2050 2160 2270]]
