<a href="https://colab.research.google.com/github/maithstartup/Notebooks-Practical-ML-Beginners/blob/master/numpy/Combine_%26_Split_an_Array.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Combine and splitting array

In [1]:
import numpy as np

In [2]:
arr1 = np.array([[1,2,3,4], [10,20,30,40]])
arr2 = np.array([[5,6,7,8], [50,60,70,80]])

### ```np.concatenate((a, b), axis=0)```

In [3]:
print(arr1)
print(arr2)

[[ 1  2  3  4]
 [10 20 30 40]]
[[ 5  6  7  8]
 [50 60 70 80]]


In [4]:
# concat along the row
cat = np.concatenate((arr1, arr2), axis=0)        
print(cat)
print(cat.shape)

[[ 1  2  3  4]
 [10 20 30 40]
 [ 5  6  7  8]
 [50 60 70 80]]
(4, 4)


In [5]:
# concat along the column
cat = np.concatenate((arr1, arr2), axis=1)    
print(cat)
print(cat.shape)

[[ 1  2  3  4  5  6  7  8]
 [10 20 30 40 50 60 70 80]]
(2, 8)


### ```np.vstack((a, b))``` 
### ```np.r_[a, b]```

In [6]:
# stack arrays vertically
cat = np.vstack((arr1, arr2))
print(cat)

[[ 1  2  3  4]
 [10 20 30 40]
 [ 5  6  7  8]
 [50 60 70 80]]


In [7]:
# stack arrays vertically
cat = np.r_[arr1, arr2]
print(cat)

[[ 1  2  3  4]
 [10 20 30 40]
 [ 5  6  7  8]
 [50 60 70 80]]


### ```np.hstack((a, b))```
### ```np.c_[a, b]```

In [8]:
# stack arrays horizontally
cat = np.hstack((arr1, arr2))
print(cat)

[[ 1  2  3  4  5  6  7  8]
 [10 20 30 40 50 60 70 80]]


In [9]:
# stack arrays horizontally
cat = np.c_[arr1, arr2]
print(cat)

[[ 1  2  3  4  5  6  7  8]
 [10 20 30 40 50 60 70 80]]


### split an array 

In [10]:
arr = np.arange(0,32).reshape(8,4)

In [11]:
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23],
       [24, 25, 26, 27],
       [28, 29, 30, 31]])

In [12]:
# split the array vertically into n evenly spaced chunks
arr1 = np.vsplit(arr, 2)
print(arr1)

[array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]]), array([[16, 17, 18, 19],
       [20, 21, 22, 23],
       [24, 25, 26, 27],
       [28, 29, 30, 31]])]


In [13]:
# split the array horizontally into n evenly spaced chunks
arr2 = np.hsplit(arr, 4)
print(arr2)

[array([[ 0],
       [ 4],
       [ 8],
       [12],
       [16],
       [20],
       [24],
       [28]]), array([[ 1],
       [ 5],
       [ 9],
       [13],
       [17],
       [21],
       [25],
       [29]]), array([[ 2],
       [ 6],
       [10],
       [14],
       [18],
       [22],
       [26],
       [30]]), array([[ 3],
       [ 7],
       [11],
       [15],
       [19],
       [23],
       [27],
       [31]])]
