<a href="https://colab.research.google.com/github/maithstartup/Notebooks-Practical-ML-Beginners/blob/master/numpy/Manipulate_an_Array.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

In [ ]:
arr = np.arange(20,30).reshape(2,5)

In [ ]:
arr

array([[20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29]])

### transpose an array

In [ ]:
# the following methods return a copy
print(arr.T)
# or 
print(np.transpose(arr))
# or
print(arr.transpose())

[[20 25]
 [21 26]
 [22 27]
 [23 28]
 [24 29]]
[[20 25]
 [21 26]
 [22 27]
 [23 28]
 [24 29]]
[[20 25]
 [21 26]
 [22 27]
 [23 28]
 [24 29]]


### transpose of a high dimensional array with specified order of axes

In [ ]:
arr1 = np.arange(16).reshape((2,2,4))
print(arr1)
print(arr1.shape)



[[[ 0  1  2  3]
  [ 4  5  6  7]]

 [[ 8  9 10 11]
  [12 13 14 15]]]
(2, 2, 4)


In [ ]:
arr1=arr1.transpose((1,2,0))
print(arr1)
print(arr1.shape)

[[[ 0  8]
  [ 1  9]
  [ 2 10]
  [ 3 11]]

 [[ 4 12]
  [ 5 13]
  [ 6 14]
  [ 7 15]]]
(2, 4, 2)


### swap axes

In [ ]:
arr1 = np.arange(16).reshape((2,2,4))
print(arr1)
print(arr1.swapaxes(1,2))

[[[ 0  1  2  3]
  [ 4  5  6  7]]

 [[ 8  9 10 11]
  [12 13 14 15]]]
[[[ 0  4]
  [ 1  5]
  [ 2  6]
  [ 3  7]]

 [[ 8 12]
  [ 9 13]
  [10 14]
  [11 15]]]


### change the shape of an array

In [ ]:
# change the shape of an array and return a copy
arr.reshape((2,5))

array([[20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29]])

In [ ]:
# change the shape of an array in place
arr.resize((5,2))

In [ ]:
arr

array([[20, 21],
       [22, 23],
       [24, 25],
       [26, 27],
       [28, 29]])

### flatten an array

In [ ]:
# return a copy
arr.flatten()    

array([20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [ ]:
# return a view
# change any element in the view will change the initial array
arr.ravel()      

array([20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [ ]:
arr

array([[20, 21],
       [22, 23],
       [24, 25],
       [26, 27],
       [28, 29]])

### append elements to an array

In [ ]:
arr = np.array([1,2,3])

In [ ]:
# append a scalar and return a copy
arr1 = np.append(arr, 4)    
print(arr1)

[1 2 3 4]


In [ ]:
# append an array and return a copy
arr2 = np.append(arr, [4,5,6])    
print(arr2)

[1 2 3 4 5 6]


### insert elements into an array

In [ ]:
# np.insert(array, position, element)

# insert a scalar at a certain position
arr3 = np.insert(arr, 1, 100)    
print(arr3)

[  1 100   2   3]


In [ ]:
# insert multiple values at a certain position
arr3 = np.insert(arr, 1, [1,2,3])    
print(arr3)
print(arr3[3])

[1 1 2 3 2 3]
3


### delete elements from an array

In [ ]:
# remove the element at position 0
arr4 = np.delete(arr, 0)    
print(arr4)

[2 3]


In [ ]:
# remove the element at multiple positions
arr4 = np.delete(arr, [0,2])    
print(arr4)

[2]


### copy an array

In [ ]:
arr = np.array([1,2,3])

In [ ]:
# the following methods are all deep copy
arr1 = np.copy(arr)
# or 
arr2 = arr.copy()
# or 
arr3 = np.array(arr, copy=True)

In [ ]:
arr=arr+10

In [ ]:
print(arr)
print(arr1)
print(arr2)
print(arr3)


[11 12 13]
[1 2 3]
[1 2 3]
[1 2 3]
