<a href="https://colab.research.google.com/github/maithstartup/Notebooks-Practical-ML-Beginners/blob/master/numpy/numpy_datatype.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Numpy **Data Types**

In [1]:
import numpy as np
import pandas as pd

In [2]:
arr=np.array([[0,1,2],[4,5,6]])

In [3]:
arr

array([[0, 1, 2],
       [4, 5, 6]])

**Attributes of array**







1.   ndim
2.   shape

1.   size
2.   dtype

1.   itemsize
2.   data














In [4]:
arr.ndim

2

In [5]:
arr.shape

(2, 3)

In [6]:
arr.size

6

In [7]:
arr.dtype

dtype('int64')

In [8]:
arr.itemsize

8

In [9]:
arr.data

#### Datatypes

In [10]:
datatypes = pd.DataFrame(
    {
        'Type': [
            'int8', 
            'uint8', 
            'int16', 
            'uint16', 
            'int or int32', 
            'uint32', 
            'int64', 
            'uint64', 
            'float16', 
            'float32', 
            'float or float64',
            'float128', 
            'complex64', 
            'complex or complex128', 
            'bool', 
            'object', 
            'string_',
            'unicode_',
        ],
        
        'Type Code': [
            'i1', 
            'u1', 
            'i2', 
            'u2', 
            'i4 or i', 
            'u4', 
            'i8', 
            'u8', 
            'f2', 
            'f4 or f', 
            'f8 or d', 
            'f16 or g', 
            'c8', 
            'c16', 
            None, 
            'O', 
            'S', 
            'U',
        ]
    }
)

In [11]:
datatypes

Type Type Code
0                    int8        i1
1                   uint8        u1
2                   int16        i2
3                  uint16        u2
4            int or int32   i4 or i
5                  uint32        u4
6                   int64        i8
7                  uint64        u8
8                 float16        f2
9                 float32   f4 or f
10       float or float64   f8 or d
11               float128  f16 or g
12              complex64        c8
13  complex or complex128       c16
14                   bool      None
15                 object         O
16                string_         S
17               unicode_         U

### Playing with Datatypes

In [12]:
arr_1=np.array([0,1,2],dtype=np.float32)

In [13]:
arr_1.dtype

dtype('float32')

In [14]:
arr_1.itemsize

4

In [15]:
arr_2=np.array([0,1,0,1,1],dtype=np.bool_)

In [16]:
print(arr_2)
print(arr_2.dtype)

[False  True False  True  True]
bool


In [17]:
arr_3 = np.array([3+2j, 3-7j], dtype="c8")
arr_3.dtype

dtype('complex64')

**Fixed Length words**

In [18]:
arr_4=np.array(["hey","join","the","","ml","course"])
print(arr_4.dtype)
print(arr_4)

<U6
['hey' 'join' 'the' '' 'ml' 'course']


In [19]:
arr_4[3]="practical"

In [20]:
arr_4

array(['hey', 'join', 'the', 'practi', 'ml', 'course'], dtype='<U6')

In [21]:
arr_5=np.array(["hey","join","the","","ml","course"],np.object)
print(arr_5.dtype)
arr_5[3]="practical"
print(arr_5)


object
['hey' 'join' 'the' 'practical' 'ml' 'course']


In [22]:
arr_4

array(['hey', 'join', 'the', 'practi', 'ml', 'course'], dtype='<U6')

Conversion

**astype**

In [23]:
arr_5 = np.array([1,2,3], dtype='int16')
print('Original Data Type: ' + str(arr_5.dtype))

arr_5 = arr_5.astype(np.float32)
print('Data Type After Conversion: ' + str(arr_5.dtype))
print(arr_5)

Original Data Type: int16
Data Type After Conversion: float32
[1. 2. 3.]


In [24]:
arr_6 = np.array([1,2,3], dtype='int16')
print('Original Data Type: ' + str(arr_6.dtype))

arr_6 = arr_6.astype(np.bool_)
print('Data Type After Conversion: ' + str(arr_6.dtype))
print(arr_6)

Original Data Type: int16
Data Type After Conversion: bool
[ True  True  True]


In [25]:
arr_7 = np.array([126,129,257], dtype='int16')
print('Original Data Type: ' + str(arr_7.dtype))

# Range of int8 [-128, 127], 258 overflows after conversion

arr_7 = arr_7.astype(np.int8)
print('Data Type After Conversion: ' + str(arr_7.dtype))
print(arr_7)

Original Data Type: int16
Data Type After Conversion: int8
[ 126 -127    1]


In [26]:
for dtype in [np.int8, np.int32, np.int64]:
   print(np.iinfo(dtype))
for dtype in [np.float32, np.float64]:
   print(np.finfo(dtype))

Machine parameters for int8
---------------------------------------------------------------
min = -128
max = 127
---------------------------------------------------------------

Machine parameters for int32
---------------------------------------------------------------
min = -2147483648
max = 2147483647
---------------------------------------------------------------

Machine parameters for int64
---------------------------------------------------------------
min = -9223372036854775808
max = 9223372036854775807
---------------------------------------------------------------

Machine parameters for float32
---------------------------------------------------------------
precision =   6   resolution = 1.0000000e-06
machep =    -23   eps =        1.1920929e-07
negep =     -24   epsneg =     5.9604645e-08
minexp =   -126   tiny =       1.1754944e-38
maxexp =    128   max =        3.4028235e+38
nexp =        8   min =        -max
--------------------------------------------------------------

[Data Types](https://numpy.org/doc/stable/reference/arrays.dtypes.html#arrays-dtypes)

[Byteorder](https://numpy.org/doc/stable/reference/generated/numpy.dtype.byteorder.html)