<a href="https://colab.research.google.com/github/maithstartup/Notebooks-Practical-ML-Beginners/blob/master/numpy/numpy_array.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**Creating Array**

In [ ]:
import numpy as np

**From python structures** 

In [ ]:
arr_1=np.array([1,2,3,4,5])

In [ ]:
arr_1

array([1, 2, 3, 4, 5])

In [ ]:
arr_2=np.array((1,2,3,4,5))

In [ ]:
arr_2

array([1, 2, 3, 4, 5])

In [ ]:
arr_3=np.array(range(10))

In [ ]:
np.array(range(5,13,2))

array([ 5,  7,  9, 11])

In [ ]:
arr_3

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
arr_4=np.array(([1,2,3],[4,5,6]))

In [ ]:
arr_4

array([[1, 2, 3],
       [4, 5, 6]])

**Intrinsic NumPy Array Creation**

In [ ]:
np.zeros((4,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [ ]:
np.zeros_like(arr_4)

array([[0, 0, 0],
       [0, 0, 0]])

In [ ]:
np.ones((3,6))

array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]])

In [ ]:
np.ones_like(arr_4)

array([[1, 1, 1],
       [1, 1, 1]])

In [ ]:
np.full((3,4),7)

array([[7, 7, 7, 7],
       [7, 7, 7, 7],
       [7, 7, 7, 7]])

In [ ]:
np.full_like(arr_4,8)

array([[8, 8, 8],
       [8, 8, 8]])

In [ ]:
np.arange(5,25,2)

array([ 5,  7,  9, 11, 13, 15, 17, 19, 21, 23])

In [ ]:
?np.arange(10,12,.2) #stop is not included in arange

In [ ]:
np.linspace(0,100,5)

array([  0.,  25.,  50.,  75., 100.])

In [ ]:
np.linspace(0,100,20) #stop is included in linspace

array([  0.        ,   5.26315789,  10.52631579,  15.78947368,
        21.05263158,  26.31578947,  31.57894737,  36.84210526,
        42.10526316,  47.36842105,  52.63157895,  57.89473684,
        63.15789474,  68.42105263,  73.68421053,  78.94736842,
        84.21052632,  89.47368421,  94.73684211, 100.        ])

In [ ]:
np.identity(6)

array([[1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 1.]])

In [ ]:
np.diag([1,2,3,4,5])

array([[1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0],
       [0, 0, 0, 0, 5]])

In [ ]:
np.diag([12,24,36,23])

array([[12,  0,  0,  0],
       [ 0, 24,  0,  0],
       [ 0,  0, 36,  0],
       [ 0,  0,  0, 23]])

In [ ]:
np.random.rand(5,5)

array([[0.18142731, 0.12494341, 0.21181761, 0.50631038, 0.34573507],
       [0.11208881, 0.46308087, 0.92727735, 0.27219776, 0.89961689],
       [0.09832615, 0.56902983, 0.23703446, 0.66993804, 0.87250159],
       [0.29384779, 0.06674199, 0.72795748, 0.07748228, 0.53884313],
       [0.11154975, 0.61487413, 0.7105135 , 0.45164471, 0.93488647]])

In [ ]:
np.random.randn(3,3)

array([[-0.59178778, -0.2410893 , -1.32804095],
       [-0.88010983, -0.62975025, -1.65044869],
       [-0.18745815, -2.56810674,  1.565871  ]])

In [ ]:
np.eye(5,k=-1)

array([[0., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.]])

**Distributions**

[resource](https://docs.scipy.org/doc/numpy-1.14.0/reference/routines.random.html)

In [ ]:
val=np.loadtxt("/content/value.txt",delimiter=",")

In [ ]:
val

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])