<a href="https://colab.research.google.com/github/maithstartup/Notebooks-Practical-ML-Beginners/blob/master/numpy/Slicing_%26_Indexing.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Slicing and indexing

In [1]:
import numpy as np

In [2]:
arr = np.array(range(100)).reshape((10,10))

In [3]:
arr

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

### select an element by row and column indices

In [4]:
print(arr[5][5])
# or more concisely
print(arr[5,5])

55
55


In [5]:
print(arr[6,7])

67


### indexing with slicing

In [6]:
print(arr[1:3, 4:6])

[[14 15]
 [24 25]]


In [7]:
temp=arr[1:3]

In [8]:
temp[:,4:6]

array([[14, 15],
       [24, 25]])

In [9]:
# ellipsis slicing: auto-complete the dimensions
arr1 = np.array(range(8)).reshape(2,2,2)

arr1
 

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [10]:
# equivalent to arr[0,:,:]
arr1[0, ...]

array([[0, 1],
       [2, 3]])

In [11]:
arr1[0]

array([[0, 1],
       [2, 3]])

In [12]:
arr1[0,:,:]

array([[0, 1],
       [2, 3]])

### assign a scalar to a slice by broadcasting

In [13]:
print(arr)
arr[1:3,:] = 100    # or simply arr[1:3]
arr[:,8:] = 0
print(arr)

[[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]
 [20 21 22 23 24 25 26 27 28 29]
 [30 31 32 33 34 35 36 37 38 39]
 [40 41 42 43 44 45 46 47 48 49]
 [50 51 52 53 54 55 56 57 58 59]
 [60 61 62 63 64 65 66 67 68 69]
 [70 71 72 73 74 75 76 77 78 79]
 [80 81 82 83 84 85 86 87 88 89]
 [90 91 92 93 94 95 96 97 98 99]]
[[  0   1   2   3   4   5   6   7   0   0]
 [100 100 100 100 100 100 100 100   0   0]
 [100 100 100 100 100 100 100 100   0   0]
 [ 30  31  32  33  34  35  36  37   0   0]
 [ 40  41  42  43  44  45  46  47   0   0]
 [ 50  51  52  53  54  55  56  57   0   0]
 [ 60  61  62  63  64  65  66  67   0   0]
 [ 70  71  72  73  74  75  76  77   0   0]
 [ 80  81  82  83  84  85  86  87   0   0]
 [ 90  91  92  93  94  95  96  97   0   0]]


In [14]:
arr[:,7]=97
print(arr)

[[  0   1   2   3   4   5   6  97   0   0]
 [100 100 100 100 100 100 100  97   0   0]
 [100 100 100 100 100 100 100  97   0   0]
 [ 30  31  32  33  34  35  36  97   0   0]
 [ 40  41  42  43  44  45  46  97   0   0]
 [ 50  51  52  53  54  55  56  97   0   0]
 [ 60  61  62  63  64  65  66  97   0   0]
 [ 70  71  72  73  74  75  76  97   0   0]
 [ 80  81  82  83  84  85  86  97   0   0]
 [ 90  91  92  93  94  95  96  97   0   0]]


In [15]:
arr[6,:6]=120

In [16]:
arr

array([[  0,   1,   2,   3,   4,   5,   6,  97,   0,   0],
       [100, 100, 100, 100, 100, 100, 100,  97,   0,   0],
       [100, 100, 100, 100, 100, 100, 100,  97,   0,   0],
       [ 30,  31,  32,  33,  34,  35,  36,  97,   0,   0],
       [ 40,  41,  42,  43,  44,  45,  46,  97,   0,   0],
       [ 50,  51,  52,  53,  54,  55,  56,  97,   0,   0],
       [120, 120, 120, 120, 120, 120,  66,  97,   0,   0],
       [ 70,  71,  72,  73,  74,  75,  76,  97,   0,   0],
       [ 80,  81,  82,  83,  84,  85,  86,  97,   0,   0],
       [ 90,  91,  92,  93,  94,  95,  96,  97,   0,   0]])

### boolean indexing

In [17]:
arr1 = np.arange(25).reshape((5,5))
bools = np.array([True, True, False, True, False])
print(arr1)
print(arr1[bools])

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [15 16 17 18 19]]


In [18]:
# negate the condition
print(arr1[~bools])    

[[10 11 12 13 14]
 [20 21 22 23 24]]


In [19]:
arr2 = np.array([1,2,3,4,5])
# multiple conditions'
print((arr2<2) | (arr2>4))
print(arr1[(arr2<2) | (arr2>4)])    

[ True False False False  True]
[[ 0  1  2  3  4]
 [20 21 22 23 24]]


### fancy indexing

In [20]:
arr = np.arange(100).reshape(10,10)

In [21]:
# select arr[3,3], arr[1,2], arr[2,1]
print(arr[[3,1,2], [3,2,1]])       

[33 12 21]


In [22]:
arr

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [23]:
# select rows 3,1,2 and columns 6,4,8 
print(arr[[3,1,2]][:, [6,4,8]])    

[[36 34 38]
 [16 14 18]
 [26 24 28]]


In [24]:
arr[[5,6,7]][:,[4,5,6]]

array([[54, 55, 56],
       [64, 65, 66],
       [74, 75, 76]])

### dimension inference

In [25]:
# dimension inference using any negative number (usually -1)
arr = np.array(range(16)).reshape((4,-1))
print(arr.shape)
arr=arr.reshape(4,2,-1)
print(arr.shape)

(4, 4)
(4, 2, 2)


### find elements/indices by conditions

In [26]:
arr = np.arange(16).reshape(4,4)

In [27]:
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [28]:
# find the elements greater than 5 and return a flattened array
print(arr[arr>5])    # or arr[np.where(arr>5)]

[ 6  7  8  9 10 11 12 13 14 15]


In [29]:
# return values based on conditions 
# np.where(condition, true_return, false_return)
print(np.where(arr>5, -1, 10))

[[10 10 10 10]
 [10 10 -1 -1]
 [-1 -1 -1 -1]
 [-1 -1 -1 -1]]


In [30]:
# find the indices of the elements on conditions
print(np.argwhere(arr>12))

[[3 1]
 [3 2]
 [3 3]]
