<a href="https://colab.research.google.com/github/maithstartup/Notebooks-Practical-ML-Beginners/blob/master/numpy/Sort_an_Array.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [2]:
arr = np.random.choice(range(20,40),size=20).reshape(2,10)

In [3]:
arr

array([[24, 34, 27, 27, 26, 39, 32, 37, 33, 30],
       [21, 38, 30, 24, 29, 31, 28, 39, 26, 38]])

Default sort used is quicksort

### sort an array along a specified axis

In [4]:
# sort along the row and return a copy
print(np.sort(arr, axis=0))   

[[21 34 27 24 26 31 28 37 26 30]
 [24 38 30 27 29 39 32 39 33 38]]


In [5]:
arr

array([[24, 34, 27, 27, 26, 39, 32, 37, 33, 30],
       [21, 38, 30, 24, 29, 31, 28, 39, 26, 38]])

In [6]:
# sort along the row in place
arr.sort(axis=0)
print(arr)

[[21 34 27 24 26 31 28 37 26 30]
 [24 38 30 27 29 39 32 39 33 38]]


In [7]:
# sort along the column and return a copy
print(np.sort(arr, axis=1))    

[[21 24 26 26 27 28 30 31 34 37]
 [24 27 29 30 32 33 38 38 39 39]]


In [8]:
# sort along the column in place
arr.sort(axis=1)    
print(arr)

[[21 24 26 26 27 28 30 31 34 37]
 [24 27 29 30 32 33 38 38 39 39]]


### compute the indices that would sort an array along a specified axis

In [9]:
arr = np.random.choice(range(20,40),size=20).reshape(2,10)

In [10]:
arr

array([[34, 39, 32, 29, 27, 23, 31, 23, 31, 30],
       [30, 36, 30, 26, 26, 31, 28, 31, 32, 23]])

In [11]:
# along the row
print(np.argsort(arr, axis=0))

[[1 1 1 1 1 0 1 0 0 1]
 [0 0 0 0 0 1 0 1 1 0]]


In [12]:
# along the column
print(np.argsort(arr, axis=1))

[[5 7 4 3 9 6 8 2 0 1]
 [9 3 4 6 0 2 5 7 8 1]]


In [13]:
# if axis=None, return the indices of a flattened array
print(np.argsort(arr, axis=None))

[19  5  7 14 13  4 16  3 12 10  9  8  6 15 17  2 18  0 11  1]


In [14]:
arr.sort()

In [15]:
arr

array([[23, 23, 27, 29, 30, 31, 31, 32, 34, 39],
       [23, 26, 26, 28, 30, 30, 31, 31, 32, 36]])

In [16]:
temp=np.array([4,6,1,4,4,4])

In [17]:
temp.sort()

In [18]:
np.argsort(temp)

array([0, 1, 2, 3, 4, 5])

In [19]:
temp2=np.array([7,3,5,30,45,2,9])

In [20]:
np.argsort(temp2)

array([5, 1, 2, 0, 6, 3, 4])